error_messages:
  nemlog_in_timeout: "Error: Login took too long, exiting..."
  insufficient_cookies: "Error: Missing session information in the cookies, exiting..."
  error_5xx: "Error: Tinglysning returned an error 5xx, exiting..."

selenium:
  chrome_options:
    - "--log-level=3"
    - "window-size=600,1000"

tinglysning:
  nemlog_in_redirect_url: "https://www.tinglysning.dk/tmv/"
  nemlog_in_success_string: "tinglysning.dk"
  nemlog_in_login_url_start: "https://nemlog-in"


rest:
  urls:
    get_property: "https://www.tinglysning.dk/tinglysning/rest/ejendom/hovednoteringsnummer?hovednoteringsnummer={0}"
    get_property_summary: "https://www.tinglysning.dk/tinglysning/rest/ejdsummarisk/{0}"